name: test-env
channels:
  - conda-forge 
dependencies:
  - python=3.6
  - black
  - coverage
  - flake8
  - h5py 
  - importnb
  - ipykernel
  - jupyter_client 
  - keras
  - matplotlib
  - nbconvert 
  - nbformat 
  - numpy
  - opencv-python
  - pathlib 
  - pytest
  - pytest-cov
  - requests
  - scikit-image
  - scikit-learn
  - tensorflow
  - tqdm
  - pip:
    - version-information 
